spring:
  datasource:
    url: jdbc:mysql://test.cm9okkpsjcm4.ap-northeast-2.rds.amazonaws.com:3306/powerlog
    username: admin
    password: admintest
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    hibernate:
      ddl-auto:create
    # 객체에 매핑되는 기존 테이블 자동 드랍 및 새로운 테이블 생성


    #powerlog?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC